name: JS Actions

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world

      - name: npm install
        run: npm ci
        working-directory: ./.github/actions/joke-action

      - name: ha-ha
        uses: ./.github/actions/joke-action
