name: JS Actions

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - run: "echo ${{ fromJSON('{\"env\": {\"a\": \"b\"}}').env.a }}"
      
      - uses: actions/checkout@v1

      - name: hello-action
        uses: ./.github/actions/hello-world

      - name: npm install
        run: npm ci
        working-directory: ./.github/actions/joke-action

      - name: ha-ha
        uses: ./.github/actions/joke-action
        id: jokes

      - name: npm install
        run: npm ci
        working-directory: ./.github/actions/issue-maker

      - name: create-issue
        uses: ./.github/actions/issue-maker
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          joke: ${{steps.jokes.outputs.joke-output}}
